trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-18.04

stages:
  - stage: build
    displayName: Build
    jobs:
      - job: build
        steps:
          - task: Npm@1
            displayName: Install Dependencies
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: install
          - task: Npm@1
            displayName: Build Application
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: custom
              customCommand: run build
  - stage: test
    displayName: Test
    jobs:
      - job: test
        steps:
          - task: Npm@1
            displayName: Install Dependencies
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: install
          - task: Npm@1
            displayName: Test
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: custom
              customCommand: run test-hl
          - task: Npm@1
            displayName: Lint
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: custom
              customCommand: run lint -- --format=stylish
          - task: Npm@1
            displayName: E2E
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: custom
              customCommand: run e2e
  - stage: analyze
    displayName: Analyze
    jobs:
      - job: analyze
        steps:
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: sonarcloud-srv-0
              organization: p2the-pretzelmen
              projectKey: P2the-pretzelmen_frontend
              projectName: P2the-pretzelmen_frontend
          - task: Npm@1
            displayName: Install Dependencies
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: install
          - task: Npm@1
            displayName: Analyze Build
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: custom
              customCommand: run build -- --prod
          - task: Npm@1
            displayName: Analyze Tests
            inputs:
              workingDir: FrontEnd/frontEnd/
              command: custom
              customCommand: run test-hl -- --watch=false --code-coverage
          - task: PublishCodeCoverageResults@1
            displayName: Publish Code Coverage
            inputs:
              codeCoverageTool: Cobertura
              reportDirectory: FrontEnd/frontend/coverage/
              summaryFileLocation: FrontEnd/frontEnd/coverage/coburtura/coverage.xml
              failIfCoverageEmpty: true
          - task: SonarCloudAnalyze@1
            displayName: Run Code Analysis
          - task: SonarCloudPublish@1
            displayName: Publish Code Analysis
