trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-18.04

stages:
  - stage: analyze
    displayName: Analyze
    jobs:
      - job: analyze
        steps:
          - task: Npm@1
            displayName: Install Dependencies
            inputs:
              workingDir: fronEnd/frontEnd/
              command: install
          - task: SonarCloudPrepare@1
            inputs:
              SonarCloud: sonarcloud-srv-0
              scannerMode: CLI
              organization: p2the-pretzelmen
              cliProjectKey: P2the-pretzelmen_frontend
              cliProjectName: P2the-pretzelmen_frontend
              cliSources: fronEnd/frontEnd/src/
          - task: Npm@1
            displayName: Analyze Build
            inputs:
              workingDir: fronEnd/frontEnd/
              command: custom
              customCommand: run build -- --prod
          - task: Npm@1
            displayName: Analyze Tests
            inputs:
              workingDir: fronEnd/frontEnd/
              command: custom
              customCommand: run test-hl -- --code-coverage
          - task: PublishCodeCoverageResults@1
            displayName: Publish Code Coverage
            inputs:
              codeCoverageTool: Cobertura
              reportDirectory: fronEnd/frontEnd/coverage/
              summaryFileLocation: fronEnd/frontEnd/coverage/cobertura-coverage.xml
              failIfCoverageEmpty: true
          - task: SonarCloudAnalyze@1
            displayName: Run Code Analysis
          - task: SonarCloudPublish@1
            displayName: Publish Code Analysis
